#!/bin/bash

# message=$1 

# npm run lint
# status=$?

# if [ "$status" != 0 ]; then
#     echo "Erro no lint"
#     exit 
# fi


# npm  test
# status=$?

# if [ "$status" != 0 ]; then
#     echo "Erro nos tests"
#     exit 
# fi


# git add .
# git commit -m "$message"
# git push

source .env

npm run build 

zip -r build.zip dist node_modules .env.prod

sshpass -p $PASSWORD scp build.zip root@128.199.12.79:projects/escolapp 
sshpass -p $PASSWORD ssh -t root@128.199.12.79 "\
  cd projects/escolapp &&\
  unzip -o build.zip &&\
  cat .env.prod > .env &&\
  pm2 restart escolapp --update-env
"