#!/bin/bash
source .env

if [[ $@ =~ "push" ]]; then 

  npm run lint 

  npm run test


  git add .
  git commit -m "$2"
  git push 

  exit 
fi



if [[ $@ =~ "dist" ]]; then 
  npm run build
fi

zip -r build.zip $@

sshpass -p $PASSWORD scp build.zip root@128.199.12.79:projects/escolapp 
sshpass -p $PASSWORD ssh -t root@128.199.12.79 "\
  cd projects/escolapp &&\
  unzip -o build.zip &&\
  cat .env.prod > .env &&\
  source ~/.nvm/nvm.sh &&\
  pm2 restart escolapp --update-env
"

