name: Github Actions CICD

on:
    push:
        branches: main

jobs:
    Tests:
        name: Tests 
        runs-on: ubuntu-latest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SPREAD_SHEET_ID:  ${{ secrets.SPREAD_SHEET_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        steps:
          - name: Checkout 
            uses: actions/checkout@v3
            
          - name: Install dependencias 
            run: npm install 

          - name: Run unit tests 
            run: npm test

    Deploy:
        runs-on: ubuntu-latest 
        needs: [Tests]
        environment: 
            name: Deploy
        steps:
            - uses: actions/checkout@v3
            - name: Install Vercel CLI
              run : npm install -g vercel@latest 
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
      
            
